
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - EmailApp
#
pool:
  vmImage: ubuntu-latest


steps:
- script: echo Hello, world! # for 'script' steps, the text of the script is put into a file and
                             # that file is executed by cmd.exe on windows or bash elsewhere.
  displayName: Run a one-line script
  condition: 'succeeded()' # https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions

# pro/con script vs task
# with script: more control. more ability to manually test on local environment (debuggging the pipeline)
# with task: if it encapsulates some useful work that would be awkward to do in a script.
#    (e.g. integrate with service connection)
# - script: sonar-scanner -Dsonar.host=https://sonarcloud.io -sonar.login=asdfasdfasdf

# azure devops has "service connections"
#   these are abstractions for some kind of login to something that a pipeline might want to login to
# so instead of defining some secret variable for the password and substituting it into this file,
#   (we CAN do that... with variable groups set up in the "library" part of "pipelines")

# service connections are NOT defined in the repo / IAC / yaml.
# they are set up in the azure devops website in the project settings.